// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_chirp_by_user_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChirpByUserId = `-- name: DeleteChirpByUserId :one
DELETE FROM chirps WHERE id = $1 AND user_id = $2 RETURNING id, created_at, updated_at, body, user_id
`

type DeleteChirpByUserIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteChirpByUserId(ctx context.Context, arg DeleteChirpByUserIdParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, deleteChirpByUserId, arg.ID, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
