// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revoke_token.sql

package database

import (
	"context"
)

const revokeToken = `-- name: RevokeToken :exec
UPDATE refresh_tokens SET revoked_at = NOW(), updated_at= NOW() WHERE token = $1 RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, token)
	return err
}
