// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: set_user_password.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users SET hashed_password = $2, updated_at= NOW() WHERE id = $1 RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type UpdateUserPasswordParams struct {
	ID             uuid.UUID
	HashedPassword string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.ID, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
