// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: set_user_email.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserMail = `-- name: UpdateUserMail :one
UPDATE users SET email = $2, updated_at= NOW() WHERE id = $1 RETURNING id, created_at, updated_at, email, hashed_password
`

type UpdateUserMailParams struct {
	ID    uuid.UUID
	Email string
}

func (q *Queries) UpdateUserMail(ctx context.Context, arg UpdateUserMailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserMail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
