POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "I need a Kerfuffle!"
}

###

POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "This has fornax and sharbert in it"
}

###

POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "This has fornax and sharbert in it. And a lot of text that keeps going and going well past one hundred and forty characters to trigger the length validation error branch instead."
}

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "test@test.com"
}

###
POST http://localhost:8080/admin/reset



###

POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "Hello, world!",
  "user_id": "d7559b46-8bde-4c9d-8981-dfd4deefae09"
}